config/routes.rb
Smile::Application.routes.draw do
  get 'index' => "amnests/index"
  resources :miles

  devise_for :amnests
  devise_for :donors

  root "pages#home"
  get 'match' => 'pages#match'
  get 'about' => 'pages#about'
  get 'login' => 'pages#login'
  get 'airlines' => 'pages#airlines'
  get 'matching' => 'pages#matching'
  get 'flight' => 'pages#flight'
  get 'receive'=> 'amnests#show'

  

end

app/models/amnest.rb
class Amnest < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :last_name, :story, :location_from, :location_to, :birthday, :dates

end

app/models/donor.rb
class Donor < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :story, :airline, :rewards
end

app/models/mile.rb
class Mile < ActiveRecord::Base
 attr_accessible :airline, :rewards, :email
end

app/controllers/amnests_controller.rb
class AmnestsController < ApplicationController
  def index
  	@amnests = Amnest.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/donors_controller.rb
class DonorsController < ApplicationController
  def registrations
  end

  def match
  end

  def about
  end

end

app/controllers/miles_controller.rb
class MilesController < ApplicationController
  before_action :set_mile, only: [:show, :edit, :update, :destroy]

  # GET /miles
  # GET /miles.json
  def index
    @miles = Mile.all
  end

  # GET /miles/1
  # GET /miles/1.json
  def show
  end

  # GET /miles/new
  def new
    @mile = Mile.new
  end

  # GET /miles/1/edit
  def edit
  end

  # POST /miles
  # POST /miles.json
  def create
    @mile = Mile.new(mile_params)

    respond_to do |format|
      if @mile.save
        format.html { redirect_to @mile, notice: 'Mile was successfully created.' }
        format.json { render action: 'show', status: :created, location: @mile }
      else
        format.html { render action: 'new' }
        format.json { render json: @mile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /miles/1
  # PATCH/PUT /miles/1.json
  def update
    respond_to do |format|
      if @mile.update(mile_params)
        format.html { redirect_to @mile, notice: 'Mile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @mile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /miles/1
  # DELETE /miles/1.json
  def destroy
    @mile.destroy
    respond_to do |format|
      format.html { redirect_to miles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mile
      @mile = Mile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mile_params
      params.require(:mile).permit(:airline, :rewards, :email)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def match
  end

  def matching
  	#map view
  	#listview
  end

  def about
  end

  def login

  end

  def airlines
  	#calculate miles based on user information login
  	#miles key or reward points
  end

  def flight
  	#flightsconfirmed
  end
end

app/helpers/amnests_helper.rb
module AmnestsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/miles_helper.rb
module MilesHelper
end

app/views/amnests/index.html.erb
<h1>Amnests index</h1>

<div class="table-responsive">
<table class="table table-striped table-hover table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th>Story</th>
    </tr>
  </thead>

  <tbody>
    <% @amnests.each do |amnest| %>
      <tr>
        <td><%= amnest.first_name %></td>
        <td><%= amnest.story %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/amnests/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/amnests/show.html.erb
<h1><%= @amnest.first_name %></h1>

app/views/donors/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/donors/show.html.erb
<h1><%= @donor.name %></h1>

app/views/layouts/_footer.html.erb
  <hr>


    <footer>
      <p>&copy; S'MILE 2014 by <a href="https://github.com/carloskcheung">Carlos Cheung</a></p>
    </footer>


    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="js/vendor/jquery-1.10.1.min.js"><\/script>')</script>

    <script src="js/vendor/bootstrap.min.js"></script>

    <script src="js/main.js"></script>

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "S'MILE", root_path, class: "navbar-brand" %>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path %></li>
        <li class="active"><%= link_to "Match", match_path %></li>
        <li><%= link_to "About", about_path %></li>
        <% if donor_signed_in? %>
          <li><%= link_to 'Edit profile', edit_donor_registration_path %></li>
          <li><%= link_to "Logout", destroy_donor_session_path, method: :delete %> </li>
        <% elsif amnest_signed_in?%>
          <li><%= link_to 'Edit profile', edit_amnest_registration_path %></li>
          <li><%= link_to "Logout", destroy_amnest_session_path, method: :delete %> </li>
        <% else %>
          <li> <%= link_to "Donor Login", new_donor_session_path %> </li>
          <li> <%= link_to "Amnest Login", new_amnest_session_path %> </li>
        <% end %>
  
      </ul> 

    </div>
  </div>
</div>

  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>S'MILE</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container page_container">
    <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
    <% end %>

  	<%= render 'layouts/header' %>
		
	  <%= yield %>
  	
  	<%= render 'layouts/footer' %>
	</div>

</body>
</html>

app/views/miles/_form.html.erb
<%= simple_form_for(@mile) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :airline %>
    <%= f.input :rewards %>
   	<%= f.input :email %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/miles/edit.html.erb
<h1>Editing mile</h1>

<%= render 'form' %>

<%= link_to 'Show', @mile %> |
<%= link_to 'Back', miles_path %>

app/views/miles/index.html.erb
<h1>Listing Miles</h1>

<div class="table-responsive">
<table class="table table-striped table-hover table-condensed">
  <thead>
    <tr>
      <th>Airline</th>
      <th>Rewards</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @miles.each do |mile| %>
      <tr>
        <td><%= mile.airline %></td>
        <td><%= mile.rewards %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<%= link_to 'New Mile', new_mile_path %>
<br />
<%= link_to 'Airlines', airlines_path %>

app/views/miles/indexsecret.html.erb
<h1>Listing Miles</h1>

<div class="table-responsive">
<table class="table table-striped table-hover table-condensed">
  <thead>
    <tr>
      <th>Airline</th>
      <th>Rewards</th>
      <th>Email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @miles.each do |mile| %>
      <tr>
        <td><%= mile.airline %></td>
        <td><%= mile.rewards %></td>
        <td><%= mile.email %></td>
        <td><%= link_to 'Show', mile %></td>
        <td><%= link_to 'Edit', edit_mile_path(mile) %></td>
        <td><%= link_to 'Destroy', mile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

app/views/miles/new.html.erb
<h1>New mile</h1>

<%= render 'form' %>

<%= link_to 'Back', miles_path %>

app/views/miles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Airline:</strong>
  <%= @mile.airline %>
</p>

<p>
  <strong>Rewards:</strong>
  <%= @mile.rewards %>
</p>

<p>
  <strong>Email:</strong>
  <%= @mile.email %>
</p>

<%= link_to 'Edit', edit_mile_path(@mile) %> |
<%= link_to 'Back', miles_path %>

app/views/pages/about.html.erb
<div class="about_container">
	<h1>About Us</h1>
	<P> We started this project at a Hack4Good event</P>
</div>

app/views/pages/airlines.html.erb
<!-- reference http://www.seatguru.com/browseairlines/browseairlines.php -->

<h1>  Airlines </h1>

<p><%= link_to 'Back', miles_path %></p>

<div class="table-responsive">
<table class="table table-striped table-hover table-condensed">
  <thead>
    <tr>
      <th>A - E</th>
      <th>F - O</th>
      <th>P - W</th>
    </tr>
  </thead>

  <tbody>
		<tr>
			<td><strong>A</strong></td>
			<td><strong>F</strong></td>
			<td><strong>P</strong></td>
		</tr>
		<tr>
			<td>Aer Lingus</td>
			<td>Fiji Airways</td>
			<td>Philippine Airlines</td>
		</tr>
		<tr>
			<td>Aeroflot</td>
			<td>Finnair</td>
			<td>Porter</td>
		</tr>
		<tr>
			<td>Aeromexico</td>
			<td>Frontier</td>
			<td></td>
		</tr>
		<tr>
			<td>Air Canada</td>
			<td></td>
			<td><strong>Q</strong></td>
		</tr>
		<tr>
			<td>Air China</td>
			<td><strong>G</strong></td>
			<td>Qantas</td>
		</tr>
		<tr>
			<td>Air France</td>
			<td>Germanwings</td>
			<td>Qatar Airways</td>
		</tr>
		<tr>
			<td>Air India</td>
			<td>go!</td>
			<td></td>
		</tr>
		<tr>
			<td>Air India Express</td>
			<td>Gol</td>
			<td><strong>R</strong></td>
		</tr>
		<tr>
			<td>Air New Zealand</td>
			<td>Gulf Air</td>
			<td>Regional Express</td>
		</tr>
		<tr>
			<td>Air Tahiti Nui</td>
			<td></td>
			<td>Royal Brunei</td>
		</tr>
		<tr>
			<td>Air Transat</td>
			<td><strong>H</strong></td>
			<td>Royal Jordanian</td>
		</tr>
		<tr>
			<td>Air Vanuatu</td>
			<td>Hainan Airlines</td>
			<td>Ryanair</td>
		</tr>
		<tr>
			<td>AirAsia</td>
			<td>Hawaiian Airlines</td>
			<td>Table Cell</td>
		</tr>
		<tr>
			<td>AirAsia X</td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td>AirBerlin</td>
			<td><strong>I</strong></td>
			<td><strong>S</strong></td>
		</tr>
		<tr>
			<td>AirTran</td>
			<td>Iberia</td>
			<td>S7 Airlines</td>
		</tr>
		<tr>
			<td>Alaska Airlines</td>
			<td>Icelandair</td>
			<td>SAS</td>
		</tr>
		<tr>
			<td>Alitalia</td>
			<td>indiGo Airlines</td>
			<td>Singapore Airlines</td>
		</tr>
		<tr>
			<td>Allegiant</td>
			<td>Island Air</td>
			<td>Skylanes</td>
		</tr>
		<tr>
			<td>American Airlines</td>
			<td></td>
			<td>South African Airways</td>
		</tr>
		<tr>
			<td>ANA</td>
			<td><strong>J</strong></td>
			<td>Southwest</td>
		</tr>
		<tr>
			<td>Asiana</td>
			<td>JAL</td>
			<td>SpiceJet</td>
		</tr>
		<tr>
			<td>Austrian</td>
			<td>Jet Airways</td>
			<td>Spirit</td>
		</tr>
		<tr>
			<td>Avianca</td>
			<td>JetBlue</td>
			<td>Sun Country</td>
		</tr>
		<tr>
			<td></td>
			<td>JetStar</td>
			<td>SWISS</td>
		</tr>
		<tr>
			<td><strong>B</strong></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td>British Airways</td>
			<td><strong>K</strong></td>
			<td><strong>T</strong></td>
		</tr>
		<tr>
			<td>Brussels Airlines</td>
			<td>Kenya Airways</td>
			<td>TACA</td>
		</tr>
		<tr>
			<td></td>
			<td>KLM</td>
			<td>TAM</td>
		</tr>
		<tr>
			<td><strong>C</strong></td>
			<td>Korean Air</td>
			<td>TAP Portugal</td>
		</tr>
		<tr>
			<td>Cathay Pacific</td>
			<td></td>
			<td>THAI</td>
		</tr>
		<tr>
			<td>China Airlines</td>
			<td><strong>L</strong></td>
			<td>Thomas Cook Airlines</td>
		</tr>
		<tr>
			<td>China Eastern</td>
			<td>LAN Airlines</td>
			<td>Thomson</td>
		</tr>
		<tr>
			<td>China Southern</td>
			<td>LOT Polish Airlines</td>
			<td>Tigerair</td>
		</tr>
		<tr>
			<td>Copa Airlines</td>
			<td>Lufthansa</td>
			<td>TUIfly</td>
		</tr>
		<tr>
			<td>Czech Airlines</td>
			<td></td>
			<td>Turkish Airlines</td>
		</tr>
		<tr>
			<td></td>
			<td><strong>M</strong></td>
			<td></td>
		</tr>
		<tr>
			<td><strong>D</strong></td>
			<td>Malaysia Airlines</td>
			<td><strong>U</strong></td>
		</tr>
		<tr>
			<td>Delta</td>
			<td>Monarch</td>
			<td>United</td>
		</tr>
		<tr>
			<td></td>
			<td></td>
			<td>US Airways</td>
		</tr>
		<tr>
			<td><strong>E</strong></td>
			<td><strong>N</strong>/td>
			<td></td>
		</tr>
		<tr>
			<td>EasyJet</td>
			<td>Norwegian</td>
			<td><strong>V</strong></td>
		</tr>
		<tr>
			<td>EL AL</td>
			<td></td>
			<td>Virgin America</td>
		</tr>
		<tr>
			<td>Emirates</td>
			<td><strong>O</strong></td>
			<td>Table Cell</td>
		</tr>
		<tr>
			<td>Ethiopian Airlines</td>
			<td>Oman Air</td>
			<td>Virgin Atlantic</td>
		</tr>
		<tr>
			<td>Etihad</td>
			<td>OpenSkies</td>
			<td>Virgin Australia</td>
		</tr>
		<tr>
			<td>EVA Air</td>
			<td></td>
			<td>Volaris</td>
		</tr>
		<tr>
			<td></td>
			<td></td>
			<td>Vueling Airlines</td>
		</tr>
		<tr>
			<td></td>
			<td></td>
			<td><br/></td>
		</tr>
		<tr>
			<td></td>
			<td></td>
			<td><strong>W</strong></td>
		</tr>
		<tr>
			<td></td>
			<td></td>
			<td>WestJet</td>
		</tr>
		<tr>
			<td></td>
			<td></td>
			<td>Wizzair</td>
		</tr>
	</tbody>
</table>
</div>

<%= link_to 'Back', miles_path %>

app/views/pages/flight.html.erb
<h1> World S'MILES Flight</h1>

<iframe width='100%' height='500px' frameBorder='0' src='http://a.tiles.mapbox.com/v3/ckc653.h815d7pg/mm/zoompan,zoomwheel,geocoder,share.html'></iframe>

<!-- <iframe src="http://bl.ocks.org/mpmckenna8/8894003" width= "1000" height= "800">
          </iframe> -->


<!-- <!DOCTYPE html>
<meta charset="utf-8">
<style>
/*//Uncomment if you want to add those lat/long lines
.graticule {
  fill: none;
  stroke: #777;
  stroke-opacity: .5;
  stroke-width: .5px;
}
 */
svg{
    Background:black;
}

.land {
  fill: #99d8c9;
}



.boundary {
  fill: none;
  stroke: purple;
  stroke-width: .5px;
}

</style>
<body>
<script src="http://d3js.org/d3.v3.min.js"></script>
<script src="http://d3js.org/topojson.v1.min.js"></script>
<script>

var width = 960,
    height = 960;

var projection = d3.geo.mercator()
    .scale((width + 1) / 2 / Math.PI)
    .translate([width / 2, height / 2])
    .precision(.1)
     .center([-0,0]);

var path = d3.geo.path()
    .projection(projection);



var graticule = d3.geo.graticule();

var svg = d3.select("body").append("svg")
    .attr("width", width)
    .attr("height", height);

svg.append("path")
    .datum(graticule)
    .attr("class", "graticule")
    .attr("d", path);

d3.json("/mbostock/raw/4090846/world-50m.json", function(error, world) {
  svg.insert("path", ".graticule")
      .datum(topojson.feature(world, world.objects.land))
      .attr("class", "land")
      .attr("d", path);

        console.table(world.objects.countries);
        
  svg.insert("path", ".graticule")
        .datum(topojson.mesh(world, world.objects.countries, function(a, b) { return a !== b; }))
      .attr("class", "boundary")
      .attr("d", path)
        ;
});

d3.select(self.frameElement).style("height", height + "px");

</script> -->

app/views/pages/home.html.erb
<div class="splash">
  <div class="inner">
    <div class="container">
      <div class="row">
        <div class="col-md-8">
          <br />
          <h1>
            Every Mile Creates A Smile
          </h1>
          <h2>
            Donate Airline-miles so refugees
            <br/>
            can fly home &amp see their families
            <br/>
            Tweet us @App_Smile
            <br />
            <br />

            <div class="row">
               <p><%= link_to "Donor Sign Up", new_donor_registration_path, class: "btn btn-success btn-lg" %>
              <%= link_to "Amnest Sign Up", new_amnest_registration_path, class: "btn btn-primary btn-lg" %></p>

            </div>

           
          </h2>
          <br />
          <br />
        </div>
        <div class="col-md-4">
          <%= image_tag '' %>
        </div>
      </div>
    </div>
  </div>
</div>



<div class="container">
  <div class="row">
    <div class="col-lg-4">
      <h2>Step 1: List Miles </h2>
      <p> Currently we allow people to list how many miles they have and be contacted by people in need of flights. In the near future, we will convert your points to miles for you. </p>
      <p><%= link_to "List S'MILEs", miles_path, class: "btn btn-default" %></p>
      
    </div>
    <div class="col-lg-4">
      <h2>Step 2: Matching System </h2>
      <p> We will contact you and do an introduction to match you with qualifed individuals. It is in the discreation of individuals to coordinate exact details for privacy purposes </p>
      <% if donor_signed_in? %>
        <p><%= link_to "S'MILE Now", matching_path, class: "btn btn-default" %></p>
        <% elsif amnest_signed_in?%>
        <p><%= link_to "S'MILE Now", matching_path, class: "btn btn-default" %></p>
        <% else %>
          <p><%= link_to "S'MILE Now", login_path, class: "btn btn-default" %></p>
      <% end %> 
   </div>
    <div class="col-lg-4">
      <h2>Step 3: Flight </h2>
      <p> We visualize on a map the people we help on a day-to-day basis </p>
      <p><%= link_to "S'MILE Flight", flight_path, class: "btn btn-default" %></p>
    </div>
  </div>
  
</div> <!-- /container -->  

     <!-- a lot of security issues need to be addressed -->

app/views/pages/login.html.erb
<div class="match_container">
	<h1> Login Below </h1>
	<%= link_to "Donor Login", new_donor_session_path, class: "btn btn-success btn-lg" %> 
	<%= link_to "Amnest Login", new_amnest_session_path, class: "btn btn-primary btn-lg" %>
</div>

app/views/pages/match.html.erb
<div class="match_container">	
	<h1>Are you a Donor or Amnest? </h1>
	<p> Our unique matching system finds the best fit for both people</p>
	
	<div class="row">

    <div class="col-lg-6">
      <h2>Donor</h2>
      <br />
        <p class="col-lg-3">Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo
        </p>
      <br />
      <p><%= link_to "Donor Sign Up", new_donor_registration_path, class: "btn btn-success btn-lg" %> </p>
    </div>
    <div class="col-lg-6">
      <h2>Amnest</h2>
      <br />
        <p class="col-lg-3">Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo
        </p>
      <br />
      <p><%= link_to "Amnest Sign Up", new_amnest_registration_path, class: "btn btn-primary btn-lg" %></p>
    </div>

 	</div>
	
</div>

app/views/pages/matching.html.erb
<h1>Donor Name</h1>

<p> List of Amnests</p>